#!/bin/tcsh -f
#$ -cwd
#$ -o GHSQG_opt_b97-m.job.o$JOB_ID
#$ -q cubs.q
#$ -j y
#$ -N q-GHSQG_opt_b97-m
#$ -pe shared 8


setenv QC /usr/software/qchem_511
source /usr/software/qchem_511/MGCF_qcenv.csh

cd $SGE_O_WORKDIR
/bin/hostname

set echo
setenv PATH /usr/software/nbo6_g16/bin:${PATH}
setenv NBOEXE /usr/software/nbo6_g16/bin/nbo6.i8.exe
awk '{ print $1 }' $PE_HOSTFILE > GHSQG_opt_b97-m.nodes
setenv QCMACHINEFILE GHSQG_opt_b97-m.nodes
setenv QCSCRATCH $SGE_O_WORKDIR/$JOB_ID
/bin/mkdir -p $QCSCRATCH
setenv QCLOCALSCR /scr/$USER/$JOB_ID
/bin/mkdir -p $QCLOCALSCR
/usr/bin/env

/usr/software/qchem_511/bin/qchem -nt 8 GHSQG_opt_b97-m.in GHSQG_opt_b97-m.out

